# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
builds:
  - id: "my-go-app"
    dir: go/my-app
    binary: mygoapp
    env:
      - CGO_ENABLED=0
      - >-
        {{- if eq .Os "darwin" }}
          {{- if eq .Arch "amd64"}}CC=o64-clang{{- end }}
          {{- if eq .Arch "arm64"}}CC=aarch64-apple-darwin20.2-clang{{- end }}
        {{- end }}
        {{- if eq .Os "windows" }}
          {{- if eq .Arch "amd64" }}CC=x86_64-w64-mingw32-gcc{{- end }}
        {{- end }}
    ignore:
      - goos: windows
        goarch: arm64