on:
  release:
    types: [published]

name: Release

jobs:
  get-release-version:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world"
      - uses: actions/github-script@v7
        id: get-release-version
        with:
          script: return "${{ github.event.release.name }}".substring(1)
          result-encoding: string
      - id: use-release-version
        run: |
          echo ${{ steps.get-release-version.outputs.version }}